// This file is auto-generated by @hey-api/openapi-ts

import type { GetActivityByIdResponse, GetPeakExpertPoolByIdResponse, GetPeakPoolByIdResponse, GetPeakPoolVoteByIdResponse, GetPeakSeasonByIdResponse } from './types.gen.js';

const activitySchemaResponseTransformer = (data: any) => {
    if (data.start_time) {
        data.start_time = new Date(data.start_time);
    }
    if (data.end_time) {
        data.end_time = new Date(data.end_time);
    }
    return data;
};

export const getActivityByIdResponseTransformer = async (data: any): Promise<GetActivityByIdResponse> => {
    data = activitySchemaResponseTransformer(data);
    return data;
};

const peakSeasonSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

export const getPeakSeasonByIdResponseTransformer = async (data: any): Promise<GetPeakSeasonByIdResponse> => {
    data = peakSeasonSchemaResponseTransformer(data);
    return data;
};

const peakPoolSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

export const getPeakPoolByIdResponseTransformer = async (data: any): Promise<GetPeakPoolByIdResponse> => {
    data = peakPoolSchemaResponseTransformer(data);
    return data;
};

const peakExpertPoolSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

export const getPeakExpertPoolByIdResponseTransformer = async (data: any): Promise<GetPeakExpertPoolByIdResponse> => {
    data = peakExpertPoolSchemaResponseTransformer(data);
    return data;
};

const peakPoolVoteSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

export const getPeakPoolVoteByIdResponseTransformer = async (data: any): Promise<GetPeakPoolVoteByIdResponse> => {
    data = peakPoolVoteSchemaResponseTransformer(data);
    return data;
};
